annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: 0.60.1
dependencies:
- condition: blackboxExporter.enabled
  name: prometheus-blackbox-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 7.1.*
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.43.*
kubeVersion: '>=1.16.0-0'
name: kube-prometheus-grafana-blackbox
type: application
version: 41.7.3
